# Conclusion

<br>
After exploring the each music features and relationship among them, we have gained a more through understanding of songs genres and observed several interesting discoveries to answer questions we came up with in the beginning.<br>
<br>

We first analyzed the basic information of each genre and plotted the number of each genres with the average popularity. One interesting finding is that the number of songs in genre edm is not equivalent to the average popularity. Even though it provides some useful information about how popular this genre is, we can't simply use it to describe the overall popularity. By further analyzing the features in each genre using density plot, we were able to select eight features: Valence, Energy, Danceability, loudness, speechiness, Accoustcness, Instrumentalness and Liveness that provide good insight of separating the genres. Then, we used histogram and boxplot to further explore how those eight features define genres and how those features are related to each other.<br>
<br>

By analyzing the correlation among features, we found that there exists some positive and negative correlations among features. Most correlations matches with our understanding toward music such as Energy and loudness are fairly highly correlated (0.68) and loudness and acousticnes are negatively correlated(-0.36) which makes sense because the louder the music is, the less acoustic the music will be. Another interesting discovery is that the danceability is negatively correlated with tempo and energy but in reality, people are more likely to dance if the energy is high or if the temp is fast. After analyzing the correlation between feaures and genres, we were able to draw conclusions on the how music features define and affect genres. By analyzing the distribution of each feature using histogram and qqplot, we discovered some more detailed information of each feature that.<br>
<br>

Despite these findings, our analysis is limited. As in our result, we cannot find very strong indicators for r&b, pop and latin, in the future we will include more features and trying to find ways to split these six music genre in a much clearer way. Moreover, our dataset does not include geological information about songs, which will affect the songs' popularity. In the future, if geological information is included, we will generate heat maps for different genre of songs and analyze the influences of geological location on popularity of different genre. Since this time we only focused on data exploration, we are not using any modelings to help up better characterize and predict genres using features. So in the future work, we could use such modelings and machine learning techniques to generate better and more meaningful insights.
